# Generated by Django 4.2.6 on 2023-10-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruits", "0002_company_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="manager",
        ),
    ]
